version: "3.3"

services:
  relaxy-exam:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./alert.rules.yaml:/etc/prometheus/alert.rules.yaml
    ports:
      - "9090:9090"
